name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: ./ch3_functions

  buildAll:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build all projects
      run: |
        for dir in ch*; do
          if [ -d "$dir" ]; then
            cd "$dir"
            cargo build --release
            cd ..
          fi
        done
